### ISSUE TITLE
French logic breaks lists

### ISSUE THREAD

**Issue by adiktofsugar** [colinta/SublimeCalculate#22]
Because of the logic for detecting comma style decimal separators (like 1,2 instead of 1.2), lists are broken. `[1,2,3]` is transformed to `[1.2.3]`. I'd recommend removing the logic entirely, since it ends up eval-ing python, which is very powerful, or you can parse the string beforehand and see if it's in a list.

Either way, you should probably mention this on your readme.

I don't mind trying to make a PR for this when I have time, but I'm not sure what your solution would be. Thanks for the plugin!

**Comment by colinta** [comment]
Hmm, good point.  Or we could check for preceding/trailing characters, they all must be a digit or `-`, that kind of thing.

**Comment by colinta** [comment]
No that's not right; in your case it would see either `1,2` or `2,3` as a French number.

**Comment by adiktofsugar** [comment]
also keep in mind you can use mixed forms: `[1.1, 2.2, 4]`, or a tuple: `(1, 2.3, 4)`

**Comment by colinta** [comment]
Yeah I'm just going to remove it, I don't see a way to make it work.

**Comment by colinta** [comment]
Breaking change, available in 3.0.0

**Comment by adiktofsugar** [comment]
Wow, so fast. Thanks a bunch!

**Comment by kpym** [comment]
I agree that my idea to replace ',' by '.' was not a good one for this package.
For the moment in my fork I stick with version 2.5, because I rally need this "french" version.
In my fork I have added also semicolon as french list separator.
I also added some trigonometric functions in degrees `cosd`, `sind`...

Another example where the "french" version breaks Calculate is : `round(sin(1),2)` (which is replaced by `round(sin(1).2)`).
In my case I have to use now `round(sin(1);2)` which is not good idea for the "official version".

This separators problem is a real mess, which is already the case in Excel for example.

I see two ways to make the things right : 
1. (bad way, but faster) : add a `substitute french` parameter in the settings (not very world friendly).
2. (better way, IMO) : add `i18n` parameter in the settings that defines the decimal and the list separator for some language and based on the selected dictionary (global Sublime setting) replace or not this separators.
